version: '3'
services:
    web:
        container_name: web
        image: uracilo/static:1
        ports:
            - "3000:3000"
        restart: always
    database:
        container_name: mysql
        build: .
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pwd